# Generated by Django 5.2.7 on 2025-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperation',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cooperation',
            old_name='cooperation_type',
            new_name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='name',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperation',
            name='restaurant_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
