# Generated by Django 5.2.7 on 2025-11-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0002_rename_submitted_at_cooperation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dish_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='cooperate.cooperation')),
            ],
        ),
    ]
