# Generated by Django 5.2.7 on 2025-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0003_cooperation_is_approved_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cooperate', 'verbose_name_plural': 'Cooperates'},
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cooperations/', verbose_name='Hình ảnh quán'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='opening_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Giờ hoạt động'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='restaurant_name',
            field=models.CharField(max_length=255, verbose_name='Tên quán'),
        ),
    ]
