# Generated by Django 5.2.4 on 2025-12-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0004_alter_cooperation_options_alter_cooperation_address_and_more'),
        ('search', '0002_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.province'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.ward'),
        ),
    ]
