# Generated by Django 5.2.4 on 2025-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0005_cooperation_province_cooperation_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
