# Generated by Django 5.2.7 on 2025-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
            ],
        ),
    ]
