# Generated by Django 5.2.7 on 2025-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='can_take_away',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_bike_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_car_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_seating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='province_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ward_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
