# Generated by Django 5.2.7 on 2025-12-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_userprofile'),
        ('food', '0005_dish_image'),
    ]

    operations = [
    ]
