# Generated by Django 5.2.7 on 2025-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_merge_0004_userprofile_0005_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/dishes/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ward_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='DishReview',
        ),
    ]
