# Generated by Django 5.2.7 on 2025-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_restaurant_closing_time_restaurant_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
