# Generated by Django 5.2.4 on 2025-12-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0006_cooperation_latitude_cooperation_longitude'),
        ('food', '0013_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishreview',
            name='cooperate_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cooperate.dish'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.dish'),
        ),
    ]
